# Generated by Django 4.1.1 on 2022-09-24 21:23

from django.db import migrations, models
import django.db.models.deletion
import store_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category_image', models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_iamge', models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to)),
                ('old_price', models.FloatField(default=0.0)),
                ('discount', models.BooleanField(default=False)),
                ('inventory', models.IntegerField(default=0)),
                ('flash_sale', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_on_delivery', models.BooleanField(default=False)),
                ('card_payment', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_out_product', to='store_api.product')),
            ],
        ),
    ]
