# Generated by Django 4.1.1 on 2022-09-24 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_chart', to='store_api.product'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
