# Generated by Django 4.1.1 on 2022-09-13 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_chart', to='store_api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
