# Generated by Django 4.1.1 on 2022-09-24 22:59

from django.db import migrations, models
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
    ]
