# Generated by Django 4.0.5 on 2022-09-15 07:51

from django.db import migrations, models
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_alter_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='chart',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
    ]
