# Generated by Django 4.1.1 on 2022-09-27 10:36

from django.db import migrations, models
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_remove_checkout_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
    ]
