# Generated by Django 4.0.5 on 2022-09-15 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_api', '0004_rename_chart_chart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
