# Generated by Django 4.1.1 on 2022-09-27 10:51

from django.db import migrations, models
import django.db.models.deletion
import store_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_in_chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store_api.chart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='image/default.jpg', upload_to=store_api.models.upload_to),
        ),
    ]
